# Generated by Django 4.0.5 on 2022-08-31 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_skill_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='user_leadership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leadership_title', models.CharField(blank=True, max_length=255, null=True)),
                ('leadership_desc', models.TextField()),
                ('leadership_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leadership', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
