# Generated by Django 4.0.5 on 2022-08-31 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_user_volunteership'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_fellowship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fellowship_title', models.CharField(blank=True, max_length=255, null=True)),
                ('fellowship_desc', models.TextField()),
                ('fellowship_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fellowship', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
