# Generated by Django 4.0.5 on 2022-09-06 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_user_career_is_currently_working'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_career',
            name='is_currently_working',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
