# Generated by Django 4.0.5 on 2022-09-06 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_user_career_is_currently_working'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_career',
            name='is_currently_working',
            field=models.BooleanField(default=False),
        ),
    ]
