# Generated by Django 4.0.5 on 2022-09-07 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_user_socialmedia'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_socialmedia',
            new_name='user_social_media',
        ),
    ]
