# Generated by Django 4.0.5 on 2022-09-08 05:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_rename_user_socialmedia_user_social_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_currently_working', models.BooleanField(default=False)),
                ('remark', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industry', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
