# Generated by Django 4.0.5 on 2022-09-08 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_user_city_user_marital_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_career',
            old_name='end_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='user_career',
            name='emp_type',
        ),
        migrations.RemoveField(
            model_name='user_career',
            name='is_currently_working',
        ),
        migrations.RemoveField(
            model_name='user_career',
            name='start_date',
        ),
    ]
