# Generated by Django 4.0.5 on 2022-09-09 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_user_fellowship_organisation_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professional_detail',
            name='is_currently_working',
        ),
    ]
