# Generated by Django 4.0.5 on 2022-09-10 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_remove_professional_detail_is_currently_working'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_industry',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='user_industry',
            name='is_currently_working',
        ),
    ]
