# Generated by Django 4.0.5 on 2022-09-21 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_work_space_tag_alter_work_space_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work_space_tag',
            old_name='tag',
            new_name='tag_name',
        ),
        migrations.RemoveField(
            model_name='work_space',
            name='tags',
        ),
        migrations.AddField(
            model_name='work_space',
            name='tags',
            field=models.ManyToManyField(related_name='workspace_tag', to='workspace.work_space_tag'),
        ),
    ]
