# Generated by Django 4.0.5 on 2022-09-29 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workspace', '0003_rename_tag_work_space_tag_tag_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('due_Date', models.DateField()),
                ('priority', models.IntegerField(blank=True, choices=[(1, 'High priority'), (2, 'medium priority'), (3, 'low priority')], null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_task', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('project_category', models.CharField(max_length=255)),
                ('open_positions', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('due_Date', models.DateField()),
                ('estimated_budget', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_project', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
