# Generated by Django 4.0.5 on 2022-10-03 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0005_resume'),
    ]

    operations = [
        migrations.DeleteModel(
            name='resume',
        ),
    ]
